databases:
  - name: mysite
    databaseName: mysite
    user: mysite

services:
  - type: web
    name: django-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn shop.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: PYTHON_VERSION
        Value: 3.11.11
      - key: WEB_CONCURRENCY
        value: 4